name: Artifacts
on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - run: cat date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 7
      - uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
