name: QA Build Auto merge
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  auto-merge:
    strategy:
      matrix:
        base: [build/qa_a, build/qa_b, main]
        head: [feature/16.0.0]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: merge
        run: |
          git switch ${{ matrix.head }}
          echo "HEAD=$HEAD" >> "${GITHUB_ENV}"
          git switch -c "${HEAD}"
          diff=$(git diff --name-only "origin/${BASE}" "${HEAD}")
          if [ -z "$diff" ]; then
            echo "No changes between ${BASE} and ${HEAD}"
            exit 0
          fi
          git push origin "${HEAD}"
          gh pr create --base "${BASE}" --head "${HEAD}" --title "Auto merge" --body "Auto merge"
          gh pr merge --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD: ${{ matrix.head }}_to_${{ matrix.base }}
          BASE: ${{ matrix.base }}
      - name: Clean up
        if: always()
        run: |
          echo "HEAD=${HEAD}"
          git push origin --delete "${HEAD}"
