name: Auto merge
on:
  pull_request:
  workflow_dispatch:

jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: merge
        run: |
          echo "${GITHUB_HEAD_REF}"
          gh pr merge "${GITHUB_HEAD_REF}" --merge
