name: Cache
on: workflow_dispatch

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: test-${{ runner.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/dummy
          restore-keys: test-${{ runner.os }}-
      - run: |
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then
            echo "dummy exists"
            exit 0;
          fi
          echo "save dummy"
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 20
      - run: ls -lh "${GITHUB_WORKSPACE}/dummy"
