name: QA Build Auto merge
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  auto-merge:
    strategy:
      matrix:
        base: [build/qa_a, build/qa_b, build/qa_c]
        head: [feature/16.0.0]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: merge
        run: |
          gh pr create --base ${{ matrix.base }} --head ${{ matrix.head }} --title "Auto merge" --body "Auto merge"
          gh pr merge --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
